pipeline {
    agent any
    
    parameters {
        string(name: 'BUILD_NUMBER', defaultValue: '', description: 'Número de construcción de la imagen a desplegar')
        string(name: 'GIT_BRANCH', defaultValue: '', description: 'Rama Git de la imagen a desplegar')
    }

    environment {
        DOCKER_IMAGE_NAME = "fleetwise-frontend-${params.GIT_BRANCH}:1.0.0-${params.BUILD_NUMBER}"
        CONTAINER_NAME = "fleetwise_frontend"
    }
 
    stages {
        stage('Detener Contenedor Existente') {
            steps {
                script {
                    if (sh(script: "docker ps -a --format '{{.Names}}' | grep -q '^${params.CONTAINER_NAME}\$'", returnStatus: true) == 0) {
                        sh "docker stop ${params.CONTAINER_NAME}"
                        sh "docker rm ${params.CONTAINER_NAME}"
                    }
                }
            }
        }

        stage('Ejecutar Contenedor Docker') {
            steps {
                script {
                    echo "Usando la imagen Docker: ${env.DOCKER_IMAGE_NAME}"
                    sh "docker run --rm --detach --name ${CONTAINER_NAME} -p 80:80 ${DOCKER_IMAGE_NAME}"
                }
            }
        }
    }
}
