pipeline {
    agent any
        stage('Deploy') {
            steps {
                sh '''BRANCH=$(echo $GIT_BRANCH)
                docker run --rm --name frontend-fleetwise -d -p 80:80 frontend-fleetwise-$BRANCH:1.0.0-$BUILD_ID'''
            }
        }
}
